ci:
  collect:
    numberOfRuns: 1
    # collect options here

  assert:
    assertions:
      categories:performance:
      - error
      - minScore: 0.85
      categories:accessibility:
      - error
      - minScore: 0.9
      categories:seo:
      - error
      - minScore: 0.9
      categories:best-practices:
      - error
      - minScore: 0.9

  upload:
    # upload options here

  server:
    # server options here

  wizard:
    # wizard options here
