[build]
publish = "exampleSite/public"
command = "cd exampleSite && hugo --gc --minify -b $URL"

[build.environment]
HUGO_VERSION = "0.98.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "cd exampleSite && hugo -D -F --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "cd exampleSite && hugo --gc --minify -b $DEPLOY_PRIME_URL"
